services:
  mongodb:
    image: mongo:8.0
    container_name: lp_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lp_db
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  elasticsearch:
    image: elasticsearch:9.4.6
    container_name: lp_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: lp_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=lp_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=linkedin_profiles
      - DATASET_PATH=data/linkedin_300_profiles.csv
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: lp_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  es_data:
